pop_comperp( ALLEEG,1, [4 ] ,[5],'addavg','on','addstd','off','alpha',0.05,'addall','on','subavg','on','suball','on',...
            'diffavg','on','diffstd','off','diffall','on','tplotopt',{'ydir',-1},'tlim',[-200 800],'ylim',[-20 20]);
[erp1 erp2 erpsub time sig] = pop_comperp( ALLEEG,1, [5],[6],'addavg','off','addstd','off','addall','off','subavg','off','suball','off',...
            'diffavg','on','diffstd','off','diffall','off','tplotopt',{'ydir',-1},'tlim',[-500 900],'ylim',[-15 15], ...
            'allerps' ,'off', 'diffonly','off');
figure; pop_spectopo(EEG, 2, [-500  1199], 'EEG' , 'percent', 50, 'freq', [6 10 22], 'freqrange',[2 50],'electrodes','off');